import { useEffect, useMemo, useState } from 'react'
import creaturesData from './assets/creatures.json'
import './App.css'

const portraits = import.meta.glob('./assets/portraits/*', { eager: true, query: '?url', import: 'default' })
const iconFiles = import.meta.glob('./assets/icons/*', { eager: true, query: '?url', import: 'default' })
const iconMap = Object.fromEntries(Object.entries(iconFiles).map(([path, url]) => [path.split('/').pop().replace(/\.png$/i, '').toLowerCase(), url]))
const gameIcon = name => iconMap[String(name || '').replace(/\.png$/i, '').toLowerCase()]
const normalizeCr = value => { const n = Number(value) || 0; if (n < .1875) return .125; if (n < .375) return .25; if (n < .75) return .5; return Math.round(n) }
const icons = {
  search: <><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></>, filter: <><path d="M4 6h16M7 12h10M10 18h4" /></>, users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75" /></>, plus: <path d="M12 5v14M5 12h14" />, x: <path d="m18 6-12 12M6 6l12 12" />, copy: <><rect x="9" y="9" width="13" height="13" rx="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" /></>, shield: <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z" />, heart: <path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1.1-1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z" />, sword: <><path d="m14.5 17.5-8-8M13 19l6-6M16 16l4 4M19 21l2-2M14.5 6.5 18 3l3-1-1 3-3.5 3.5M5 14l-2 2 5 5 2-2" /></>, chevron: <path d="m9 18 6-6-6-6" />, trash: <><path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6" /></>,
}
const Icon = ({ name, size = 20 }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]}</svg>
const hydrateItems = items => (items || []).map(item => ({ ...item, desc: item.description, icon: gameIcon(item.icon) }))
const creatures = creaturesData.map((raw, index) => ({
  ...raw,
  id: `${raw.resref}-${index}`,
  desc: raw.description,
  race: raw.type,
  cr: normalizeCr(raw.cr),
  portrait: portraits[`./assets/portraits/${raw.portrait}`],
  classes: hydrateItems(raw.classes),
  feats: hydrateItems(raw.feats),
  skills: hydrateItems(raw.skills),
  spells: hydrateItems(raw.spells),
})).sort((a, b) => a.cr - b.cr || a.name.localeCompare(b.name))
const bands = [['All threats', 'all'], ['CR 0–2', 'low'], ['CR 3–7', 'mid'], ['CR 8–15', 'high'], ['CR 16+', 'epic']]
const formatCr = v => Number.isInteger(v) ? v : v === .125 ? '⅛' : v === .25 ? '¼' : v === .5 ? '½' : v

const CodexList = ({ items, empty }) => items.length ? <div className="codex-list">{items.map((item, i) => <details className="codex-item" key={`${item.name}-${i}`}><summary>{item.icon ? <img src={item.icon} alt="" /> : <span className="fallback-icon">◆</span>}<span><strong>{item.name}</strong><small>{item.kind}{item.rank != null ? ` · Rank ${item.rank}` : item.level != null ? ` · Level ${item.level}` : ''}{item.uses > 1 ? ` · ×${item.uses}` : ''}</small></span><Icon name="chevron" size={16} /></summary>{item.desc && <p>{item.desc}</p>}</details>)}</div> : <p className="codex-empty">{empty}</p>

function CreatureCodex({ creature }) {
  const [tab, setTab] = useState('abilities')
  const tabs = [['abilities', 'Stats'], ['feats', `Feats ${creature.feats.length}`], ['skills', `Skills ${creature.skills.length}`], ['spells', `Powers ${creature.spells.length}`]]
  return <section className="codex"><nav>{tabs.map(([id, label]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}>{label}</button>)}</nav>
    {tab === 'abilities' && <div><div className="ability-grid">{Object.entries(creature.abilities).map(([key, value]) => <span key={key}><small>{key}</small><strong>{value}</strong></span>)}</div><h3>Classes</h3><CodexList items={creature.classes} empty="No class data recorded." /></div>}
    {tab === 'feats' && <CodexList items={creature.feats} empty="No feats recorded." />}
    {tab === 'skills' && <CodexList items={creature.skills} empty="No trained skills recorded." />}
    {tab === 'spells' && <CodexList items={creature.spells} empty="No spells or special powers recorded." />}
  </section>
}

function App() {
  const [query, setQuery] = useState(''), [race, setRace] = useState('All'), [band, setBand] = useState('all'), [selected, setSelected] = useState(null), [teamOpen, setTeamOpen] = useState(false), [copied, setCopied] = useState(false)
  const [filtersOpen, setFiltersOpen] = useState(false), [sort, setSort] = useState('name')
  const [advanced, setAdvanced] = useState({ className: '', feat: '', spell: '', minCr: '', maxCr: '', minHp: '', minAc: '', str: '', dex: '', con: '', int: '', wis: '', cha: '' })
  const [team, setTeam] = useState(() => { try { return JSON.parse(localStorage.getItem('nwn-warband') || '[]').map(c => ({ ...c, cr: normalizeCr(c.cr) })) } catch { return [] } })
  useEffect(() => localStorage.setItem('nwn-warband', JSON.stringify(team)), [team])
  const races = useMemo(() => ['All', ...new Set(creatures.map(c => c.race))], [])
  const filterOptions = useMemo(() => ({ classes: [...new Set(creatures.flatMap(c => c.classes.map(x => x.name)))].sort(), feats: [...new Set(creatures.flatMap(c => c.feats.map(x => x.name)))].sort(), spells: [...new Set(creatures.flatMap(c => c.spells.map(x => x.name)))].sort() }), [])
  const activeAdvanced = Object.values(advanced).filter(value => value !== '').length
  const filtered = useMemo(() => {
    const has = (items, value) => !value || items.some(item => item.name.toLowerCase() === value.toLowerCase())
    const list = creatures.filter(c => (c.name.toLowerCase().includes(query.toLowerCase()) || c.desc.toLowerCase().includes(query.toLowerCase())) && (race === 'All' || c.race === race) && (band === 'all' || band === 'low' && c.cr <= 2 || band === 'mid' && c.cr >= 3 && c.cr <= 7 || band === 'high' && c.cr >= 8 && c.cr <= 15 || band === 'epic' && c.cr >= 16) && has(c.classes, advanced.className) && has(c.feats, advanced.feat) && has(c.spells, advanced.spell) && (advanced.minCr === '' || c.cr >= Number(advanced.minCr)) && (advanced.maxCr === '' || c.cr <= Number(advanced.maxCr)) && (advanced.minHp === '' || c.hp >= Number(advanced.minHp)) && (advanced.minAc === '' || c.ac >= Number(advanced.minAc)) && ['str', 'dex', 'con', 'int', 'wis', 'cha'].every(stat => advanced[stat] === '' || c.abilities[stat] >= Number(advanced[stat])))
    const sorts = { name: (a, b) => a.name.localeCompare(b.name), crAsc: (a, b) => a.cr - b.cr || a.name.localeCompare(b.name), crDesc: (a, b) => b.cr - a.cr || a.name.localeCompare(b.name), hp: (a, b) => b.hp - a.hp, ac: (a, b) => b.ac - a.ac, str: (a, b) => b.abilities.str - a.abilities.str, dex: (a, b) => b.abilities.dex - a.abilities.dex }
    return list.sort(sorts[sort])
  }, [query, race, band, advanced, sort])
  const clearFilters = () => { setQuery(''); setRace('All'); setBand('all'); setAdvanced({ className: '', feat: '', spell: '', minCr: '', maxCr: '', minHp: '', minAc: '', str: '', dex: '', con: '', int: '', wis: '', cha: '' }) }
  const totalCr = team.reduce((s, c) => s + c.cr, 0), totalHp = team.reduce((s, c) => s + c.hp, 0), isAdded = c => team.some(x => x.id === c.id)
  const toggle = c => setTeam(t => t.some(x => x.id === c.id) ? t.filter(x => x.id !== c.id) : t.length < 6 ? [...t, c] : t)
  const copy = async () => { await navigator.clipboard.writeText(team.map(c => c.resref).join(' ')); setCopied(true); setTimeout(() => setCopied(false), 1800) }
  return <div className="app-shell">
    <header className="topbar"><div className="brand-mark">N</div><div className="brand-copy"><span>Neverwinter Nights</span><strong>Warband Forge</strong></div><button className="party-button" onClick={() => setTeamOpen(true)}><Icon name="users" /><span>{team.length}/6</span></button></header>
    <main><section className="hero"><div className="hero-kicker"><i />Muster your party<i /></div><h1>Choose your <em>champions</em></h1><p>Build a warband worthy of legend.</p><div className="rune-divider">◆</div></section>
      <section className="finder"><div className="search-wrap"><Icon name="search" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search the bestiary..." aria-label="Search creatures" />{query && <button onClick={() => setQuery('')}><Icon name="x" size={16} /></button>}</div><div className="select-row"><label className="sort-control"><span>Creature type</span><select value={race} onChange={e => setRace(e.target.value)}>{races.map(x => <option key={x}>{x}</option>)}</select></label><label className="sort-control"><span>Challenge</span><select value={band} onChange={e => setBand(e.target.value)}>{bands.map(([l, v]) => <option key={v} value={v}>{l}</option>)}</select></label><label className="sort-control"><span>Sort</span><select value={sort} onChange={e => setSort(e.target.value)}><option value="name">Name A–Z</option><option value="crAsc">CR: low first</option><option value="crDesc">CR: high first</option><option value="hp">Highest vitality</option><option value="ac">Highest defense</option><option value="str">Highest strength</option><option value="dex">Highest dexterity</option></select></label><button className={activeAdvanced ? 'filter-trigger active' : 'filter-trigger'} onClick={() => setFiltersOpen(true)}><Icon name="filter" /><span>More filters</span>{activeAdvanced > 0 && <b>{activeAdvanced}</b>}</button></div></section>
      {(race !== 'All' || band !== 'all' || activeAdvanced > 0) && <div className="active-filters">{race !== 'All' && <button onClick={() => setRace('All')}>{race}<Icon name="x" size={12} /></button>}{band !== 'all' && <button onClick={() => setBand('all')}>{bands.find(x => x[1] === band)?.[0]}<Icon name="x" size={12} /></button>}{Object.entries(advanced).filter(([, value]) => value !== '').map(([key, value]) => <button key={key} onClick={() => setAdvanced(current => ({ ...current, [key]: '' }))}>{key === 'className' ? 'Class' : key === 'minCr' ? 'Min CR' : key === 'maxCr' ? 'Max CR' : key === 'minHp' ? 'Min HP' : key === 'minAc' ? 'Min AC' : key.toUpperCase()}: {value}<Icon name="x" size={12} /></button>)}<button className="clear-chip" onClick={clearFilters}>Clear all</button></div>}
      <div className="results-head"><h2>The Bestiary</h2><span>{filtered.length} creatures</span></div><section className="creature-grid">{filtered.map(c => <article className={`creature-card ${isAdded(c) ? 'is-added' : ''}`} key={c.id}><button className="portrait-button" onClick={() => setSelected(c)}><img src={c.portrait} alt="" loading="lazy" /><span className="cr-badge"><small>CR</small>{formatCr(c.cr)}</span><span className="card-vignette" /></button><div className="card-body" onClick={() => setSelected(c)}><span className="race-label">{c.race}</span><h3>{c.name}</h3><div className="quick-stats"><span><Icon name="heart" size={14} />{c.hp}</span><span><Icon name="shield" size={14} />{c.ac}</span></div></div><button className="add-button" onClick={() => toggle(c)} disabled={!isAdded(c) && team.length >= 6}><Icon name={isAdded(c) ? 'x' : 'plus'} size={18} /></button></article>)}</section>
      {!filtered.length && <div className="empty-state"><span>✦</span><h3>No creature answers the call</h3><button onClick={clearFilters}>Clear filters</button></div>}
    </main>
    <button className="mobile-party-dock" onClick={() => setTeamOpen(true)}><span className="dock-portraits">{team.slice(0, 3).map(c => <img src={c.portrait} alt="" key={c.id} />)}{!team.length && <Icon name="users" />}</span><span><strong>{team.length ? 'View warband' : 'Your warband awaits'}</strong><small>{team.length ? `${formatCr(totalCr)} total CR · ${team.length}/6 chosen` : 'Choose up to 6 creatures'}</small></span><Icon name="chevron" /></button>
    {filtersOpen && <div className="overlay filter-overlay" onMouseDown={e => e.target === e.currentTarget && setFiltersOpen(false)}><aside className="filter-sheet"><div className="sheet-handle" /><div className="filter-sheet-head"><div><span className="hero-kicker">Refine the hunt</span><h2>Bestiary Filters</h2></div><button className="close-button" onClick={() => setFiltersOpen(false)}><Icon name="x" /></button></div><div className="filter-scroll">
      <div className="filter-section"><h3>Training & powers</h3><label><span>Class</span><select value={advanced.className} onChange={e => setAdvanced({ ...advanced, className: e.target.value })}><option value="">Any class</option>{filterOptions.classes.map(x => <option key={x}>{x}</option>)}</select></label><label><span>Feat</span><input list="feat-options" value={advanced.feat} onChange={e => setAdvanced({ ...advanced, feat: e.target.value })} placeholder="Any feat" /><datalist id="feat-options">{filterOptions.feats.map(x => <option key={x} value={x} />)}</datalist></label><label><span>Spell or power</span><input list="spell-options" value={advanced.spell} onChange={e => setAdvanced({ ...advanced, spell: e.target.value })} placeholder="Any spell" /><datalist id="spell-options">{filterOptions.spells.map(x => <option key={x} value={x} />)}</datalist></label></div>
      <div className="filter-section"><h3>Combat thresholds</h3><div className="number-grid"><label><span>Min CR</span><input type="number" min="0" value={advanced.minCr} onChange={e => setAdvanced({ ...advanced, minCr: e.target.value })} placeholder="Any" /></label><label><span>Max CR</span><input type="number" min="0" value={advanced.maxCr} onChange={e => setAdvanced({ ...advanced, maxCr: e.target.value })} placeholder="Any" /></label><label><span>Min vitality</span><input type="number" min="0" value={advanced.minHp} onChange={e => setAdvanced({ ...advanced, minHp: e.target.value })} placeholder="Any" /></label><label><span>Min defense</span><input type="number" min="0" value={advanced.minAc} onChange={e => setAdvanced({ ...advanced, minAc: e.target.value })} placeholder="Any" /></label></div></div>
      <div className="filter-section"><h3>Minimum abilities</h3><div className="stat-filter-grid">{['str', 'dex', 'con', 'int', 'wis', 'cha'].map(stat => <label key={stat}><span>{stat}</span><input type="number" min="0" value={advanced[stat]} onChange={e => setAdvanced({ ...advanced, [stat]: e.target.value })} placeholder="—" /></label>)}</div></div>
    </div><div className="filter-sheet-actions"><button className="clear-filter-action" onClick={clearFilters}>Reset</button><button className="apply-filter-action" onClick={() => setFiltersOpen(false)}>Show {filtered.length} creatures</button></div></aside></div>}
    {selected && <div className="overlay" onMouseDown={e => e.target === e.currentTarget && setSelected(null)}><section className="detail-sheet"><button className="close-button" onClick={() => setSelected(null)}><Icon name="x" /></button><div className="detail-content"><span className="race-label">{selected.race}</span><h2>{selected.name}</h2><div className="detail-desc"><div className="detail-portrait"><span className="cr-badge"><small>CR</small>{formatCr(selected.cr)}</span><img src={selected.portrait} alt="" /></div><p className="creature-lore">{selected.desc}</p></div><div className="detail-stats"><span><Icon name="heart" /><small>Vitality</small><strong>{selected.hp}</strong></span><span><Icon name="shield" /><small>Defense</small><strong>{selected.ac}</strong></span><span><Icon name="sword" /><small>Strength</small><strong>{selected.abilities.str || '—'}</strong></span></div><CreatureCodex creature={selected} /><button className={`primary-action ${isAdded(selected) ? 'remove' : ''}`} disabled={!isAdded(selected) && team.length >= 6} onClick={() => toggle(selected)}><Icon name={isAdded(selected) ? 'x' : 'plus'} />{isAdded(selected) ? 'Remove from warband' : team.length >= 6 ? 'Warband is full' : 'Add to warband'}</button></div></section></div>}
    {teamOpen && <div className="overlay team-overlay" onMouseDown={e => e.target === e.currentTarget && setTeamOpen(false)}><aside className="team-sheet"><div className="sheet-handle" /><div className="team-title"><div><span className="hero-kicker">Ready for battle</span><h2>Your Warband</h2></div><button className="close-button" onClick={() => setTeamOpen(false)}><Icon name="x" /></button></div><div className="team-summary"><div><small>Total challenge</small><strong>{formatCr(totalCr)}</strong></div><div><small>Combined vitality</small><strong>{totalHp}</strong></div><div><small>Slots</small><strong>{team.length}<i>/6</i></strong></div></div><div className="team-roster">{team.map((c, i) => <div className="team-member" key={c.id}><span className="member-number">0{i + 1}</span><img src={c.portrait} alt="" /><span><strong>{c.name}</strong><small>{c.race} · CR {formatCr(c.cr)}</small></span><button onClick={() => toggle(c)}><Icon name="trash" size={18} /></button></div>)}{!team.length && <div className="empty-roster"><Icon name="users" size={38} /><h3>No allies yet</h3><p>Choose creatures from the bestiary to form your warband.</p><button onClick={() => setTeamOpen(false)}>Explore the bestiary</button></div>}</div>{team.length > 0 && <div className="team-actions"><button className="copy-action" onClick={copy}><Icon name="copy" />{copied ? 'Copied to clipboard!' : 'Copy party for chat'}</button><button className="clear-action" onClick={() => setTeam([])}>Disband</button></div>}</aside></div>}
  </div>
}
export default App
